### PR TITLE
Spit out error if the /home/pi doesn't exist

### PR DESCRIPTION
**Pull request by Drachenkaetzchen**
This PR implements a check for `/home/pi`. This is done purely in the nginx config, with a custom HTTP 418 error page to inform the user of the issue.

- Error code 418 was chosen because it's not used anywhere else, so the error page shouldn't be triggered by something bogus
- The check for `/home/pi` is done with nginx' default rewrite module
- The image was put onto the image, in case the docs site is re-organized and the image link is lost.

image

### CODE REVIEW

**Comment by raymondh2** [comment]
I like this change and would like to see this implemented

**Comment by KwadFan** [comment]
Working already on a solution.

https://github.com/KwadFan/user-rename

**Comment by KwadFan** [comment]
@Drachenkaetzchen Thank you for this PR. I'd choose another route. Please see #128. Maybe you could extend that to show a message in browser that a "rename fix" is in progress?

Regards

**Comment by KwadFan** [comment]
Closed due #128

**Pull request closed without merging**
