### PR TITLE
Fix distro naming

### PR DESCRIPTION
**Pull request by jottr**
Raspbian and Raspberry Pi OS are two different distros.  
See [this blog post](https://www.tomshardware.com/news/raspberry-pi-os-no-longer-raspbian).  
This distro uses Raspberry Pi OS as a base. This PR removes all references to Raspbian.

### CODE REVIEW

**Comment by meteyou** [comment]
thx for the PR. i have to merge this PR first (https://github.com/raymondh2/MainsailOS/pull/59), and then i can check if there is any overlap.

**Comment by KwadFan** [comment]
Hello jottr,
Thanks for your work. Unfortunatly, you see the Build Check has failed. But we listen to our Users and I will change that to name it correctly. I will also give you a credit for mentioning that.

FIY: I have read the blog post you linked. Yes, technically your are right but this is in my head. 
Quote:
Raspberry Pi OS
Your Raspberry Pi needs an operating system to work. This is it. Raspberry Pi OS (previously called Raspbian) is our official supported operating system.
[Raspberry Pi OS](https://www.raspberrypi.com/software/)

Regards

**Comment by jottr** [comment]
The build check failed not because of the changes I introduced (they are cosmetic after all). 
You'll see the [same error](https://github.com/raymondh2/MainsailOS/runs/4157180847?check_suite_focus=true#step:7:1374) on the build checks of the other currently open PR.

I'd suggest to pin image versions instead of building from `latest` to make builds reproducible.

**Comment by KwadFan** [comment]
> The build check failed not because of the changes I introduced (they are cosmetic after all). You'll see the [same error](https://github.com/raymondh2/MainsailOS/runs/4157180847?check_suite_focus=true#step:7:1374) on the build checks of the other currently open PR.
> 
> I'd suggest to pin image versions instead of building from `latest` to make builds reproducible.

This is what PR #59 does, there is "buster" used. In you case it trys to build against bullseye.
[Checkout this please.](https://github.com/raymondh2/MainsailOS/runs/4157180847?check_suite_focus=true#step:7:1361)
Bullseye will become base Image in the future but there are several things to be tested and our used software needs some changes. For Example klipper uses python2 to build the firmware. We want to wait till this is also python3 based.
Therefor we stay at "buster" at the moment.

**Pull request closed without merging**
